language: node_js
node_js:
- '0.10'
- '0.12'
- '4'
- '5'
- '6'
- '7'
- '8'
install:
- bin/installDeps.sh
- export GIT_HASH=$(git rev-parse --verify --short HEAD)
- npm install ep_test_line_attrib
script:
- tests/frontend/travis/runner.sh
addons:
  sauce_connect:
    username: webzwo0i
  jwt:
    secure: k3Z8mFw341lrK70hh/JiP8s61h233lQ9UpQlFUX1YNL0rK3/yD0mRrdmHTafRKUZPqXYMM6P2VvKs1lYzo/5gj9zXlgaaj3rsSG3zpX88Rn5Cv69C08x0me1cqVbapRR1obL7QGoQJNvtVTHvD4rgRxivL19QEepznToc+I8x0W4p78cLZOJH5+wH3I8zW9R9upnBAj+10gMAh1TKpvle/P31x6DovnoxyyAjt56VQOlfqRk0hV6KKwEF1d5uM8k9KJJbmIyu7Qj/prdrdG5bvYDWErYzRSb8NC7w+U2BePtiTOfnIvRO+5zIAqS239OGj7Gf0hc2WS+1yWRQnWqfSv1m1AV3CUir8z1/O7uQBW6Mkme/t1/U+z7t1rtTaA1Jfz3FxWO96FkZbeh18JaMAq5dH5g8JLKBCuwk2W2xXD5t/pcCeJaYKP6/8/06j4LO7Xm3t15KuHyIWrw0UaahubpywfssgvSVY31moTvUAUW6he9qOqnRBMAhlY+PryiWVyvkeXJjNbh/86BBky5wF3Mh/1VkjJ61IiQ4EP0O56dBTez8IBPxE7rugo2sfAM227BlHues5Qf5KcY4S78UlnfLyRkM98QshMUrmMvEzMaR/4F1CwliUSny/DQt3LY9n3xjpBJZOLxueXO7Rzd/FGJMzL9umZQLezoIqL+kAg=
