language: node_js

node_js:
  - 'v12'

services:
  - docker

cache: false

env:
  global:
    - secure: "WnTHjwEk7ZijPMUpAY9Cz7WzGVTdTsYjTx4uDbyVeV7u3z7/EgnFapYLv5g/CSmErZ1RZmtcqeFEbtnxvMis4+RIbvHi4TepJSKVbl1v4G00sOqYu8BuWWE7fhq6Lf6cSARMrGYNMz7kZvT1RjgzYqPhkcSZz0wsQ0eZ/aHDJtVjvLsvLUyQ2WfWKbe6AAc7gczPT/465I6EVQJxBU6jALZTcPQPVhsFrrmQUcoEhLEffqg0njF1M7URanFte+q2VLiCIKsLFRTvzwElbi8qgcoGlwz+KjR7R6iGJ5UcpH32hCflGAmsmxWFP8ljSISp/0PyNfggfEMEuMC7AwK2+AjmK/1pB36kFyfmopD/fkekYKWCr4W62sa8Yxbkbee1Jwm4HXE0Ar+GbIB4Vsy7eDKCEfi26NtohG3zh+CJLNjGye8HuW/7dfjK+1WD8oO/15HTuAvtZzaQ29rc9zybv9AsfVY9nJ4q/U7byKTmFJ0AmAeafl5JBoI0C0z5Oy6C3U/8wfb+Dg9+RufUyDNqfuYxjSTqzdJwkHweLBYfZyr+ONn8UAh5QUvljwUSUgEEVQxxELN5H/SbrtjzXfAKbrcXe58VtExeWSQXfpYU0PbkPFe1MxOgghu3H03wa+XVznmpWJVEUDq75g4xzN8X/l3QzraqGxHHa0LsiZhtkik="
    - secure: "VPrilB4O46SV97p8xkEe6oFo5s8wnrzDKEj/iIGmarAFqX0xTp3rHvtPlwNGtqlSPFlExSF0E+r9R4FjLkkI25R31rF3sMjGp2ib+7OSmNoG+ue7w1Tu+KFTioKBvYQ7QtcurcZ9l0jYp91J5s0PpuICr+LzClgbcfBotJTdzeD+OgdLm9cogouLzgFoq1Arrqf1qVHIJXhs7TLFQpUORsbCwi20cWc/R2ZTV3aD+4E3uvGIb2C+EpKwc70BFr8Ex4hJTzcnd07CRVwSkdAjGqtwGWF3qlf0sV1KC4qF1Nf0txVQTVoABw9nva5Rz5ixxaELXUFi3IaxFl38zcDIpIq9f8x7ZU/cjVoW8mV0L2IivQNGntC2XdDWfQzqUun1ZtqMkcK9csoaqg/eex2TQ+cOFjOywsQu2F9mKEwZ+coyK9fkTA/EkGAFeJjzycB+slbDUGlbPEVJ0mnloSfo/RyXB6Dh1zy3UjJt23VtM80pxjlO5eddK2KF08IorJdwCBvSbwiGLV5fY03gvnT94x8pWkj4Yy+YjaWVD5CASASF7rrj4EuH5bREgTwXNsAiJPVFAIwcgEuU/FWW8fS/0DrXZjnXcUI/FQ84GVUTU/o54+Tu/JnQmhIL0LfXifF+6PdQacStA8I0jJKvy5t5oCdDq22GEYqL7cGiyfsU2qY="

addons:
  sauce_connect: true

jobs:
  include:
    - name: "Test the Frontend"
      install:
        - "sudo apt install -y socat"
        - "socat TCP-LISTEN:4444,fork,reuseaddr ssl:ondemand.us-west-1.saucelabs.com:443"
        - "bin/installDeps.sh"
        - "export GIT_HASH=$(git rev-parse --verify --short HEAD)"
      script:
        - "tests/frontend/travis/runner.sh"
    - name: "Run the Backend tests"
      install:
        - "bin/installDeps.sh"
        - "cd src && npm install && cd -"
      script:
        - "tests/frontend/travis/runnerBackend.sh"
    - name: "Test the Dockerfile"
      install:
        - "cd src && npm install && cd -"
      script:
        - "docker build -t etherpad:test ."
        - "docker run -d -p 9001:9001 etherpad:test && sleep 3"
        - "cd src && npm run test-container"
    - name: "Load test Etherpad"
      install:
        - "bin/installDeps.sh"
        - "cd src && npm install && cd -"
        - "npm install -g etherpad-load-test"
        # I set loadTest to true
        - "sed 's/\"loadTest\": false,/\"loadTest\": true,/g' settings.json.template > settings.json"
      script:
        - "tests/frontend/travis/runnerLoadTest.sh"
