language: node_js

node_js:
  - 'v10'
  - 'v12'
  - 'v14'

services:
  - docker

cache: false

install:
  - "bin/installDeps.sh"
  - "export GIT_HASH=$(git rev-parse --verify --short HEAD)"

script:
  - "tests/frontend/travis/runner.sh"

env:
  global:
    - secure: "bl1joSAW93ohJ9MvxauQT99T9m01wEldU+mwDHzGjTqwCuXLrY7+dlTGvwfxHMgnqgsw9VYxJ6BEmBT94IEjD6HSrCuyLFkNbyL6Hw29LXmnU5ZCYt/pz6N4vFiEimT7MyanHNTwmPqgyXkVp+UWKRZqVI1AtVK4Q19QGx/1jkQZZN6qGoifBGmg2v0NWlkw1MD9dkck65IWogdETXz9AwwcgMQ+wPpjhN0I32wNOR3RgiZY0Vm17KFzGVBqXXuaQb6XAMwNk1Mv9JcjSOBAtaR/ev1+uqvxmGTNacELpbvTfAHWd1m7UEetrkmTNqdEuSl//04oyypnKQU0vaqC2hiTb0aCc9YBj5xUGJ8Rsqvwlr6/wbz8VuVCFBVoQoHmldINWh7+5t6TdScrpGHb6nR3/s2GagO4T7i1TDSNcXgpHc0ZMK58hJoI6i+VZGbzOcR3ClJR75lF+QJB1kH0jmYPGGCzF1eTFtsAFuMwYSaRPl7iJZzXUEnwmTNSAVI3qgo+YnH8fWMxmzfuUhQqvcFClj6LOHIo8VtRA4mGnRdWFsqFzQKbWj2elgrSV2CQcfmiQhKQRzjc5lwk2cX5UADL519v5mrUof/8lipIq/TKz7HFhuhvjBTbLIuiLVnfg/lQJQNSaIqnQXLiIhCYLa6bXBAnZWPnOuBOGeqOdpo="
		- secure: "ZesfRbi/dPcPlHe6BtJ+0vDNcjC3lPCLhEaBYhhoTPuRPPxANtG5GsbbYbafq6CiD07FcCcyxllETnkcpmXo0SHmz+vxgmJoacG4RfrzXX04j6VsfEzH5XSs3IYu1c7UrdyIFqFiDeWF3fb3EqzWlbqLnlR/ZvapL8lF7YhKiX0Yd5bkbcKrKnih/wbshXCai2dAdoR69vEFGlI9RZbkQwVRxXPWvOuW2M6laqtMWl6iiZJz/fAQI97mZRNrCaimsuvcj14nBj/pFtflK5E9fR1IeazgiPlrXvrjUuD0PVsT/3sH9c7FuTep5nDOd7fhXIwCBMg/PhDLFfAfq0Ux7LpwULUuBr8ogn91pgdnuCkPVysvLJTE9yVVfWMSlKuNc7iDGDwMp1Q3H3kspyPBUQUeAlfJeRKDPhKmDDHfyzun/P3w1G3aI5kjkradXykY2LldHQeai58aWhpIZSK789qLBlC88+F+Y1Q3/04AoLIoY1Thw7jHrOWvmYFogWH51LjtdbKOhwLbKfjVVrjA8BQmvEgopJsJkvj1Vg4EFw/vn7VnoHQV5yB6O18fRBukflIb/m3dc1bxC9mNGZX7DtXirS3DmwUDvzwyz6AIFcu4VlGr7UEytDthFq07khBlhM8JSgI5otWFVR0tEkzxzUHGl+QTAqHG5BssLRznmig="

jobs:
  include:
    # we can only frontend tests from the ether/ organization and not from forks.
    # To request tests to be run ask a maintainer to fork your repo to ether/
    - if: fork = false
      name: "Test the Frontend"
      install:
        - "tests/frontend/travis/sauce_tunnel.sh"
        - "bin/installDeps.sh"
        - "export GIT_HASH=$(git rev-parse --verify --short HEAD)"
      script:
        - "tests/frontend/travis/runner.sh"
    - name: "Run the Backend tests"
      install:
        - "bin/installDeps.sh"
        - "cd src && npm install && cd -"
      script:
        - "tests/frontend/travis/runnerBackend.sh"
    - name: "Test the Dockerfile"
      install:
        - "cd src && npm install && cd -"
      script:
        - "docker build -t etherpad:test ."
        - "docker run -d -p 9001:9001 etherpad:test && sleep 3"
        - "cd src && npm run test-container"
    - name: "Load test Etherpad"
      install:
        - "bin/installDeps.sh"
        - "cd src && npm install && cd -"
        - "npm install -g etherpad-load-test"
        # I set loadTest to true
        - "sed 's/\"loadTest\": false,/\"loadTest\": true,/g' settings.json.template > settings.json"
      script:
        - "tests/frontend/travis/runnerLoadTest.sh"
