language: node_js
node_js:
  - "0.10"
install:
  - "bin/installDeps.sh"
  - "export GIT_HASH=$(git rev-parse --verify --short HEAD)"
before_script:
  - "tests/frontend/travis/sauce_tunnel.sh"
script:
  - "tests/frontend/travis/runner.sh"
env:
  global:
jdk:
  - oraclejdk6
